husky code for PR
TRAILab/TRAILBot pull request #10
Opened 2023-06-02 19:58 UTC by nickoenig37

The following files allow for the 2D NAV2 stack to work on the husky as well as to move the husky with the remote.

2023-06-02 23:05 UTC, MarcAntoineLavoie reviewed
Which of these files are different from the humble branch of the husky code? Why is this not a new repo? Same for pointcloud to laserscan, why is this copied here?

Remove the /.vscode files, they are specific to your machine

2023-06-02 23:05 UTC, MarcAntoineLavoie commented on husky/husky_base/launch/localization_launch.py
> +# Copyright (c) 2018 Intel Corporation
Is this used?

2023-06-02 23:05 UTC, MarcAntoineLavoie commented on husky/husky_base/package.xml
> +<?xml-model href="http://download.ros.org/schema/package_format2.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
needs cleanup

2023-06-02 23:05 UTC, MarcAntoineLavoie commented on husky/husky_bringup/launch/accessories.launch.py
> +import os
Do we need this? We are using different sensors, no?

2023-06-12 15:32 UTC, barzanisar requested changes
I got build errors when I followed the readme so some dependencies need to be installed before colcon build. I was able to launch the husky base on my laptop. I didn't review the rest of the code (cz I think it needs time to understand how nav2 works which I will do in the future).

2023-06-12 15:32 UTC, barzanisar commented on husky/README.md
> +```
colcon build fails due to pcap.h not found. 

To install all package dependencies, run:
cd ~/trail_ws
rosdep install --from-paths src --ignore-src --rosdistro humble -r -y

To only install libpcap, run:
sudo -H apt-get install -y libpcap0.8-dev

2023-06-12 15:32 UTC, barzanisar commented on husky/README.md
> +Making sure that the husky is turned input:
what does "turned input" mean?

2023-06-12 20:25 UTC, barzanisar commented on husky/README.md
> +  - cd ~/ros2_ws rosdep install --from-paths src --ignore-src --rosdistro humble -r -y
There should be a new line between these two:
cd ~/ros2_ws 
rosdep install --from-paths src --ignore-src --rosdistro humble -r -y

2023-06-12 20:36 UTC, barzanisar approved these changes

2023-06-12 20:37 UTC, merged