added 3d tracking node
TRAILab/TRAILBot pull request #13
Opened 2023-06-08 13:59 UTC by Nathan903

2023-06-12 16:04 UTC, stevenwaslander reviewed
Just minor cleanup, let's wrap this up quickly!

2023-06-12 16:04 UTC, stevenwaslander commented on perception/tracking3d/LidarCameraSubscriber.py
> +    ])
Note there should be a proper way to do this in ROS2.  @jacobdeery  can clarify

2023-06-12 16:04 UTC, stevenwaslander commented on perception/tracking3d/LidarCameraSubscriber.py
> +
Do we really need these to be global? Can't you just pass them in where needed?

2023-06-12 16:31 UTC, Nathan903 commented on perception/tracking3d/LidarCameraSubscriber.py
> +    LEFT_EYE = 1
this will only be used in one function and will never change so i think it will be more clear leaving it inside the function?

2023-06-12 16:31 UTC, Nathan903 commented on perception/tracking3d/LidarCameraSubscriber.py
> +    get the heading angle of the person, in degree, relative to the center
yes this is the angle from the camera to the person.

2023-06-13 03:59 UTC, MarcAntoineLavoie approved these changes
looks good!

2023-06-13 04:43 UTC, stevenwaslander requested changes

2023-06-13 04:43 UTC, stevenwaslander commented on tracking3d/human_detection/LidarCameraSubscriber.py
> +def read_space_seperated_matrix(string):
separated, not seperated.

2023-06-13 04:43 UTC, stevenwaslander commented on tracking3d/human_detection/LidarCameraSubscriber.py
> +    # Find the indices of the k nearest poitns
points

2023-06-13 04:43 UTC, stevenwaslander commented on tracking3d/human_detection/LidarCameraSubscriber.py
> +        return 0.4
Why is this returning .4?

2023-06-13 04:43 UTC, stevenwaslander commented on tracking3d/human_detection/LidarCameraSubscriber.py
> +    print("\n\nDEBUG MODE ON1\n\n")
Why ON1?

2023-06-13 04:47 UTC, Nathan903 commented on tracking3d/human_detection/LidarCameraSubscriber.py
> +        return 0.4
changed to ```distance_where_lidar_stops_working = 0.4```

2023-06-13 04:47 UTC, Nathan903 commented on tracking3d/human_detection/LidarCameraSubscriber.py
> +    print("\n\nDEBUG MODE ON1\n\n")
typo

2023-06-13 04:55 UTC, stevenwaslander approved these changes

2023-06-13 04:55 UTC, merged